on:
  workflow_call:    
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Does it work?
        run: echo "Hello World"
  and_again:
    runs-on: ubuntu-latest
    steps:
      - name: Does it work again?
        run: echo "Hello World Again"
